services:
  minio:
    image: minio/minio
    container_name: minio_server
    expose:
      - "9000"
      - "9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: mybucket
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - turinabol_net

  db:
    image: postgres:17-alpine
    container_name: postgresql
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: always
    networks:
      - turinabol_net

  redis:
    image: redis:7.0.15
    container_name: redis
    expose:
      - 6379
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - turinabol_net

  gateway:
    build:
      context: gateway_api
      dockerfile: Dockerfile
    image: turinabolum:latest
    container_name: turinabolum
    ports:
      - "8000:8000"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=mybucket
      - MINIO_ENDPOINT_URL=http://minio:9000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_ENV=settings
    depends_on:
      - minio
      - db
      - redis
    restart: always
    networks:
      - turinabol_net

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: turinabolum-frontend:latest
    container_name: turinabolum-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    depends_on:
      - gateway
    restart: always

  worker:
    build:
      context: gateway_api
      dockerfile: Dockerfile
    image: turinabolum:latest
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=mybucket
      - MINIO_ENDPOINT_URL=http://minio:9000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_ENV=settings
    depends_on:
      - gateway
    entrypoint: celery -A config worker --loglevel=info
    restart: always
    scale: 3

volumes:
  redis_data:
  postgres_data:
  minio-data:

networks:
  turinabol_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/16"
