services:
  minio:
    image: minio/minio
    container_name: minio_server
    expose:
      - "9000"
      - "9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: mybucket
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - turinabol_net

  db:
    image: postgres:17-alpine
    container_name: postgresql
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: always
    networks:
      - turinabol_net

  redis:
    image: redis:7.0.15
    container_name: redis
    expose:
      - 6379
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - turinabol_net

  os01:
    image: opensearchproject/opensearch:2.19.1
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m"
      node.name: os01
      discovery.seed_hosts: os01 #,os02,os03
      cluster.initial_master_nodes: os01 #,os02,os03
      plugins.security.ssl.transport.pemkey_filepath: certificates/os01/os01.key
      plugins.security.ssl.transport.pemcert_filepath: certificates/os01/os01.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/os01/os01.key
      plugins.security.ssl.http.pemcert_filepath: certificates/os01/os01.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      bootstrap.memory_lock: "true"
      network.host: "0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data1:/usr/share/opensearch/data"
      - "./opensearch/certs:/usr/share/opensearch/config/certificates:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    expose:
      - 9200
      - 9600
    restart: always
    networks:
      - turinabol_net

  gateway:
    build:
      context: gateway_api
      dockerfile: Dockerfile
    image: turinabolum:latest
    container_name: turinabolum
    ports:
      - "8000:8000"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=mybucket
      - MINIO_ENDPOINT_URL=http://minio:9000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_ENV=settings
    depends_on:
      - minio
      - db
      - redis
      - os01
    restart: always
    networks:
      - turinabol_net

  worker:
    build:
      context: gateway_api
      dockerfile: Dockerfile
    image: turinabolum:latest
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=mybucket
      - MINIO_ENDPOINT_URL=http://minio:9000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_ENV=settings
    depends_on:
      - gateway
    entrypoint: celery -A config worker --loglevel=info
    restart: always
    scale: 3
    networks:
      - turinabol_net

  disk_dump_service:
    build:
      context: disk_dump_service
      dockerfile: Dockerfile
    image: turinabolum_disk_dump_service:latest
    environment:
      - MINIO_ENDPOINT=localhost:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_SECURE=False
      - OPENSEARCH_HOST=localhost:9200
      - OPENSEARCH_INDEX_PREFIX=plaso
      - MAX_WORKERS=4
      - TEMP_DIR=/tmp
    depends_on:
      - os01
    restart: always
    scale: 1
    networks:
      - turinabol_net

volumes:
  redis_data:
  postgres_data:
  minio-data:
  os-data1:

networks:
  turinabol_net:
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/23"
