# Generated by Django 5.2.5 on 2025-09-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_dumpupload ALTER COLUMN dump_file TYPE character varying(500);",
            reverse_sql="ALTER TABLE core_dumpupload ALTER COLUMN dump_file TYPE character varying(100);"
        ),
    ]
