# Generated by Django 5.2.5 on 2025-09-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_increase_dump_file_length'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_dumpupload ALTER COLUMN original_filename TYPE character varying(500);",
            reverse_sql="ALTER TABLE core_dumpupload ALTER COLUMN original_filename TYPE character varying(255);"
        ),
    ]
